version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "cafe"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: always
    volumes:
      - "~/.pg-data:/var/lib/postgresql/data/pgdata"

  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/cafe"
      JDBC_DATABASE_USERNAME: "postgres"
      JDBC_DATABASE_PASSWORD: "root"
    volumes:
      - "~/images/appContainer:/app/images"
    restart: always
    links:
      - db